# Generated by Django 2.1 on 2019-03-21 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=500)),
                ('date_time', models.CharField(blank=True, default='', max_length=500)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
