# Generated by Django 2.1 on 2019-03-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0006_auto_20190321_1036'),
        ('Queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdvisorInfo.AdvisorData'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
