# Generated by Django 2.1 on 2019-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queue', '0002_auto_20190321_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
