# Generated by Django 2.1 on 2019-03-21 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queue', '0003_auto_20190321_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
