# Generated by Django 2.1 on 2019-03-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Queue', '0004_auto_20190321_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='price',
        ),
    ]
