# Generated by Django 2.1 on 2019-04-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Queue', '0006_queue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(blank=True, default='waiting', max_length=500),
        ),
    ]
