# Generated by Django 2.1 on 2019-04-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0009_auto_20190326_1613'),
        ('Queue', '0007_auto_20190402_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='name',
        ),
        migrations.AddField(
            model_name='queue',
            name='available',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='AdvisorInfo.available'),
        ),
    ]
