# Generated by Django 2.1 on 2019-04-10 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0010_advisordata_user'),
        ('Queue', '0008_auto_20190402_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='queue',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdvisorInfo.AdvisorData'),
        ),
    ]
