# Generated by Django 2.1 on 2019-04-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Queue', '0009_auto_20190410_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='detail',
            new_name='description',
        ),
    ]
