# Generated by Django 2.1 on 2019-04-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Queue', '0010_auto_20190423_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='description',
            new_name='detail',
        ),
    ]
