# Generated by Django 2.1 on 2019-05-02 16:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0012_advisordata_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Queue', '0011_auto_20190423_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=500)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='waiting', max_length=500)),
                ('available', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='AdvisorInfo.available')),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdvisorInfo.AdvisorData')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
