# Generated by Django 2.1 on 2019-05-02 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0012_advisordata_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Queue', '0012_queueadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueueAdmin',
            new_name='QueueAd',
        ),
    ]
