# Generated by Django 2.1 on 2019-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('telephone', models.CharField(default='', max_length=13)),
                ('department', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('tax_num', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('expertise', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
