# Generated by Django 2.1 on 2019-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisordata',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='advisordata',
            name='department',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='advisordata',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='advisordata',
            name='expertise',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='advisordata',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='advisordata',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='advisordata',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='advisordata',
            name='tax_num',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='advisordata',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
