# Generated by Django 2.1 on 2019-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0002_auto_20190225_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisordata',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
