# Generated by Django 2.1 on 2019-03-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0004_auto_20190308_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisordata',
            old_name='tax_num',
            new_name='tax_number',
        ),
    ]
