# Generated by Django 2.1 on 2019-03-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0005_auto_20190308_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_display', models.BooleanField()),
                ('advisor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdvisorInfo.AdvisorData')),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nine', models.CharField(blank=True, default='', max_length=500)),
                ('ten', models.CharField(blank=True, default='', max_length=500)),
                ('eleven', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='available',
            name='datetime',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdvisorInfo.time'),
        ),
    ]
