# Generated by Django 2.1 on 2019-03-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0006_auto_20190321_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='eleven',
        ),
        migrations.RemoveField(
            model_name='time',
            name='nine',
        ),
        migrations.RemoveField(
            model_name='time',
            name='ten',
        ),
        migrations.AddField(
            model_name='time',
            name='afternoon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='time',
            name='morning',
            field=models.BooleanField(default=True),
        ),
    ]
