# Generated by Django 2.1 on 2019-03-26 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0007_auto_20190326_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
