# Generated by Django 2.1 on 2019-03-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0008_available_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available',
            old_name='datetime',
            new_name='free_time',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='afternoon',
            new_name='is_display',
        ),
        migrations.RemoveField(
            model_name='available',
            name='date',
        ),
        migrations.RemoveField(
            model_name='time',
            name='morning',
        ),
        migrations.AddField(
            model_name='available',
            name='free_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='available',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
