# Generated by Django 2.1 on 2019-04-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0010_advisordata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisordata',
            name='expertise',
        ),
    ]
