# Generated by Django 2.1 on 2019-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdvisorInfo', '0011_remove_advisordata_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisordata',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
