# Generated by Django 2.1 on 2019-04-23 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Queue', '0009_auto_20190410_1802'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdvisorInfo', '0012_advisordata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('advisor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AdvisorInfo.AdvisorData')),
                ('queue', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Queue.Queue')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdoc', models.CharField(blank=True, default='', max_length=500)),
                ('doc', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Document.Document')),
            ],
        ),
    ]
