# Generated by Django 2.1 on 2019-04-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
