# Generated by Django 2.1 on 2019-04-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_auto_20190423_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='advisor',
        ),
    ]
