# Generated by Django 2.1 on 2019-04-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_auto_20190423_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdoc',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='subdoc',
            name='status',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
