# Generated by Django 2.1 on 2019-04-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0006_auto_20190423_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf')),
            ],
        ),
        migrations.RemoveField(
            model_name='subdoc',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subdoc',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='subdoc',
            name='status',
            field=models.CharField(blank=True, default='incomplete', max_length=500),
        ),
        migrations.AddField(
            model_name='file',
            name='subdoc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Document.SubDoc'),
        ),
    ]
