# Generated by Django 2.1 on 2019-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0008_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
