# Generated by Django 2.1 on 2019-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0009_auto_20190424_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='pdf'),
        ),
    ]
