# Generated by Django 2.1 on 2019-04-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0011_superfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfile',
            name='file',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
