# Generated by Django 2.1 on 2019-05-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0012_auto_20190424_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfile',
            name='file',
            field=models.ImageField(blank=True, upload_to='products/%Y_%m_%d'),
        ),
    ]
