# Generated by Django 2.1 on 2019-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0013_auto_20190506_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfile',
            name='file',
            field=models.ImageField(blank=True, upload_to='file/%Y_%m_%d'),
        ),
    ]
