# Generated by Django 2.1 on 2019-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0014_auto_20190507_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='superfile',
            name='status',
            field=models.CharField(blank=True, default='waiting', max_length=500),
        ),
    ]
