# Generated by Django 2.1 on 2019-05-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0015_superfile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superfile',
            name='status',
        ),
    ]
